<?xml version="1.0" encoding="utf-8"?><Database Name="QLSieuThi" Class="QLSTDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-GKNTKFSD\SQLEXPRESS;Initial Catalog=QLSieuThi;Integrated Security=True" SettingsObjectName="DAO.Properties.Settings" SettingsPropertyName="QLSieuThiConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CTPhieuNhap" Member="CTPhieuNhaps">
    <Type Name="CTPhieuNhap">
      <Column Name="SoPhieuNhap" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuongNhap" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DonGiaNhap" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="HangHoa_CTPhieuNhap" Member="HangHoa" ThisKey="MaHang" OtherKey="MaHang" Type="HangHoa" IsForeignKey="true" />
      <Association Name="PhieuNhapHang_CTPhieuNhap" Member="PhieuNhapHang" ThisKey="SoPhieuNhap" OtherKey="SoPhieuNhap" Type="PhieuNhapHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuXuatHang" Member="PhieuXuatHangs">
    <Type Name="PhieuXuatHang">
      <Column Name="SoPhieuXuat" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayTaoPXH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PhieuXuatHang_CTPhieuXuatHang" Member="CTPhieuXuatHangs" ThisKey="SoPhieuXuat" OtherKey="SoPhieuXuat" Type="CTPhieuXuatHang" />
      <Association Name="NhanVien_PhieuXuatHang" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTPhieuXuatHang" Member="CTPhieuXuatHangs">
    <Type Name="CTPhieuXuatHang">
      <Column Name="SoPhieuXuat" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuongXuat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="PhieuXuatHang_CTPhieuXuatHang" Member="PhieuXuatHang" ThisKey="SoPhieuXuat" OtherKey="SoPhieuXuat" Type="PhieuXuatHang" IsForeignKey="true" />
      <Association Name="HangHoa_CTPhieuXuatHang" Member="HangHoa" ThisKey="MaHang" OtherKey="MaHang" Type="HangHoa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTHoaDonBanHang" Member="CTHoaDonBanHangs">
    <Type Name="CTHoaDonBanHang">
      <Column Name="MaHang" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoHoaDon" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="HangHoa_CTHoaDonBanHang" Member="HangHoa" ThisKey="MaHang" OtherKey="MaHang" Type="HangHoa" IsForeignKey="true" />
      <Association Name="HoaDonBanHang_CTHoaDonBanHang" Member="HoaDonBanHang" ThisKey="SoHoaDon" OtherKey="SoHoaDon" Type="HoaDonBanHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DangNhap" Member="DangNhaps">
    <Type Name="DangNhap">
      <Column Name="TaiKhoan" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NhanVien_DangNhap" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HangHoa" Member="HangHoas">
    <Type Name="HangHoa">
      <Column Name="MaHang" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NgaySX" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HSD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoLuongTon" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HangHoa_CTPhieuNhap" Member="CTPhieuNhaps" ThisKey="MaHang" OtherKey="MaHang" Type="CTPhieuNhap" />
      <Association Name="HangHoa_CTPhieuXuatHang" Member="CTPhieuXuatHangs" ThisKey="MaHang" OtherKey="MaHang" Type="CTPhieuXuatHang" />
      <Association Name="HangHoa_CTHoaDonBanHang" Member="CTHoaDonBanHangs" ThisKey="MaHang" OtherKey="MaHang" Type="CTHoaDonBanHang" />
      <Association Name="LoaiHangHoa_HangHoa" Member="LoaiHangHoa" ThisKey="MaLoai" OtherKey="MaLoai" Type="LoaiHangHoa" IsForeignKey="true" />
      <Association Name="NhaCungCap_HangHoa" Member="NhaCungCap" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCungCap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonBanHang" Member="HoaDonBanHangs">
    <Type Name="HoaDonBanHang">
      <Column Name="SoHoaDon" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="VAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaKHTT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HoaDonBanHang_CTHoaDonBanHang" Member="CTHoaDonBanHangs" ThisKey="SoHoaDon" OtherKey="SoHoaDon" Type="CTHoaDonBanHang" />
      <Association Name="KhachHangThanThiet_HoaDonBanHang" Member="KhachHangThanThiet" ThisKey="MaKHTT" OtherKey="MaThe" Type="KhachHangThanThiet" IsForeignKey="true" />
      <Association Name="NhanVien_HoaDonBanHang" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHangThanThiet" Member="KhachHangThanThiets">
    <Type Name="KhachHangThanThiet">
      <Column Name="MaThe" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinhKH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SDTKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChiKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Diem" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="KhachHangThanThiet_HoaDonBanHang" Member="HoaDonBanHangs" ThisKey="MaThe" OtherKey="MaKHTT" Type="HoaDonBanHang" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiHangHoa" Member="LoaiHangHoas">
    <Type Name="LoaiHangHoa">
      <Column Name="MaLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiHangHoa_HangHoa" Member="HangHoas" ThisKey="MaLoai" OtherKey="MaLoai" Type="HangHoa" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCungCap" Member="NhaCungCaps">
    <Type Name="NhaCungCap">
      <Column Name="MaNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChiNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDTNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NhaCungCap_HangHoa" Member="HangHoas" ThisKey="MaNCC" OtherKey="MaNCC" Type="HangHoa" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinhNV" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Luong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SDTNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChiNv" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NhanVien_PhieuXuatHang" Member="PhieuXuatHangs" ThisKey="MaNV" OtherKey="MaNV" Type="PhieuXuatHang" />
      <Association Name="NhanVien_DangNhap" Member="DangNhaps" ThisKey="MaNV" OtherKey="MaNV" Type="DangNhap" />
      <Association Name="NhanVien_HoaDonBanHang" Member="HoaDonBanHangs" ThisKey="MaNV" OtherKey="MaNV" Type="HoaDonBanHang" />
      <Association Name="NhanVien_PhieuNhapHang" Member="PhieuNhapHangs" ThisKey="MaNV" OtherKey="MaNV" Type="PhieuNhapHang" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuNhapHang" Member="PhieuNhapHangs">
    <Type Name="PhieuNhapHang">
      <Column Name="SoPhieuNhap" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayTaoPNH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PhieuNhapHang_CTPhieuNhap" Member="CTPhieuNhaps" ThisKey="SoPhieuNhap" OtherKey="SoPhieuNhap" Type="CTPhieuNhap" />
      <Association Name="NhanVien_PhieuNhapHang" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
</Database>